# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Matrix" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD drone-matrix.exe c:\drone-matrix.exe
ENTRYPOINT [ "c:\\drone-matrix.exe" ]
