[[constraint]]
  branch = "master"
  name = "github.com/drone/drone-template-lib"

[[constraint]]
  branch = "master"
  name = "github.com/matrix-org/gomatrix"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/microcosm-cc/bluemonday"
  version = "1.0.0"
